# Generated by Django 6.0.5 on 2026-06-01 14:48

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfmanagermodel',
            name='pdf',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='pdfs/'),
        ),
    ]
