# Generated by Django 6.0.5 on 2026-06-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfmanager', '0002_alter_pdfmanagermodel_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfmanagermodel',
            name='pdf',
            field=models.URLField(max_length=500),
        ),
    ]
