# Generated by Django 6.0.5 on 2026-06-01 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivityModel',
        ),
    ]
